// <auto-generated />
using API_PRUEBA_PROGRESO3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_PRUEBA_PROGRESO3.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240124041652_CreacionDB")]
    partial class CreacionDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_PRUEBA_PROGRESO3.Models.Tarea", b =>
                {
                    b.Property<int>("idTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTarea"));

                    b.Property<string>("descripcionTarea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estadoTarea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreTarea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idTarea");

                    b.ToTable("Tarea");

                    b.HasData(
                        new
                        {
                            idTarea = 1,
                            descripcionTarea = "20 ejercicios",
                            estadoTarea = "Pendiente",
                            nombreTarea = "Matematicas"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
